apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-creator-app
  labels:
    app: message-creator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-creator
  template:
    metadata:
      labels:
        app: message-creator
    spec:
      containers:
      - name: message-creator
        image: ghcr.io/{.registry}/reliable-apps/message-creator:{.tag}
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env: 
          - name: "PORT"
            value: "8080"
          - name: "RECEIVER_URL"
            value: "http://message-receiver/api/message/receive"
          - name: "INSTRUMENTATIONKEY"
            valueFrom:
              secretKeyRef:
                name: appconfig
                key: applicationInsightsConnectionString
          - name: "EVENTHUB_NAME"
            valueFrom:
              secretKeyRef:
                name: appconfig
                key: eventHubName
          - name: "EVENTHUB_CONNECTIONSTRING"
            valueFrom:
              secretKeyRef:
                name: appconfig
                key: eventHubConnectionString