apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-creator-app
  labels:
    app: message-creator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: message-creator
  template:
    metadata:
      labels:
        app: message-creator
    spec:
      containers:
      - name: message-creator
        image: ghcr.io/{.registry}/reliable-apps/message-creator:{.tag}
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "400m"
        env: 
          - name: "PORT"
            value: "8080"
          - name: "VERSION"
            value: "{.version}"
          - name: "ASPNETCORE_URLS"
            value: "http://+:8080"
          - name: "RECEIVER_URL"
            value: "http://message-receiver/api/message/receive"
          - name: "HttpClient__EnableRetry"
            value: "{.enableRetry}"
          - name: "HttpClient__EnableBreaker"
            value: "{.enableBreaker}"
          - name: "ApplicationInsights__ConnectionString"
            valueFrom:
              secretKeyRef:
                name: appconfig
                key: applicationInsightsConnectionString
          - name: "EVENTHUB_NAME"
            valueFrom:
              secretKeyRef:
                name: appconfig
                key: eventHubName
          - name: "EVENTHUB_CONNECTIONSTRING"
            valueFrom:
              secretKeyRef:
                name: appconfig
                key: eventHubConnectionString