apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-receiver-app
  labels:
    app: message-receiver
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: message-receiver
  template:
    metadata:
      labels:
        app: message-receiver
    spec:
      containers:
      - name: message-receiver
        image: ghcr.io/{.registry}/reliable-apps/message-receiver:{.tag}
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1000m"
          limits:
            memory: "2000Mi"
            cpu: "2000m"
        env: 
          - name: "PORT"
            value: "8080"
          - name: "VERSION"
            value: "{.version}"
          - name: "ASPNETCORE_URLS"
            value: "http://+:8080"
          - name: "SINK_URL"
            value: "http://message-sink/"
          - name: "HttpClient__EnableRetry"
            value: "{.enableRetry}"
          - name: "HttpClient__EnableBreaker"
            value: "{.enableBreaker}"
          - name: "EventHub__EventHubName"
            valueFrom:
              secretKeyRef:
                name: appconfig
                key: eventHubName
          - name: "EVENTHUB__EventHubConnectionString"
            valueFrom:
              secretKeyRef:
                name: appconfig
                key: eventHubConnectionString
          - name: "EventHub__BlobConnectionString"
            valueFrom:
              secretKeyRef:
                name: appconfig
                key: blobConnectionString
          - name: "ApplicationInsights__ConnectionString"
            valueFrom:
              secretKeyRef:
                name: appconfig
                key: applicationInsightsConnectionString