apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-sink-app
  labels:
    app: message-sink
spec:
  replicas: 3
  selector:
    matchLabels:
      app: message-sink
  template:
    metadata:
      labels:
        app: message-sink
    spec:
      containers:
      - name: message-sink
        image: ghcr.io/{.registry}/reliable-apps/message-sink:{.tag}
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1000m"
          limits:
            memory: "2000Mi"
            cpu: "2000m"
        env: 
          - name: "PORT"
            value: "8080"
          - name: "VERSION"
            value: "{.version}"
          - name: "ASPNETCORE_URLS"
            value: "http://+:8080"
          - name: "IpRateLimiting__EnableEndpointRateLimiting"
            value: "{.enableRateLimiting}"
          - name: "ConnectionStrings__CosmosApi"
            valueFrom:
              secretKeyRef:
                name: appconfig
                key: cosmosConnectionString
          - name: "ApplicationInsights__ConnectionString"
            valueFrom:
              secretKeyRef:
                name: appconfig
                key: applicationInsightsConnectionString