apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ca-receiver-creator
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: message-receiver-app
  targetCPUUtilizationPercentage: 20